# Generated by Django 3.0.7 on 2021-12-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=8)),
            ],
        ),
    ]
